version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  pre_build:
    commands:
      - npm i --production
  build:
    commands:
      - mkdir build
      - mv -v index.js util node_modules build/
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file sam-template.yml --s3-bucket grundgetta
artifacts:
  type: zip
  files:
    - template.yml
    - sam-template.yml
