version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install --production
      - zip -rX index.zip index.js util/ node_modules
      - aws s3 rb --force s3://grundgetta
      - aws s3 mb s3://grundgetta
      - aws s3 cp index.zip s3://grundgetta/
      - aws cloudformation package --template-file template.yml --output-template-file sam-template.yml --s3-bucket s3://grundgetta
      - echo "$ALEXA_SKILL_KIT_ID"
artifacts:
  type: zip
  files:
    - template.yml
    - sam-template.yml
