version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install --production
  post_build:
    commands:
      - mkdir deploy
      - cp -R index.js util node_modules deploy/
      - aws cloudformation package --template-file template.yml --output-template-file sam-template.yml --s3-bucket grundgetta
artifacts:
  type: zip
  files:
    - template.yml
    - sam-template.yml
